name: BedwarsItemAddon
api-version: '1.13'
main: me.ram.bedwarsitemaddon.Main
version: ${project.version}
author: Ram
depend: [ BedwarsRel, ProtocolLib ]
softdepend: [ BedwarsScoreBoardAddon ]
website: "https://github.com/TheRamU/BedwarsItemAddon"

commands:
  bedwarsitemaddon:
    aliases: [ bwia ]

permissions:
  bedwarsitemaddon.reload:
    default: op
  bedwarsitemaddon.updatecheck:
    default: op
